name: docker_build

on: [push]

jobs:
  docker_build_job:
    runs-on: ubuntu-latest
    name: docker build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build action
        uses: ./ # Uses an action in the root directory
        id: run